import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/componants/Header'
import Hero from '@/componants/Hero'
import AfterHero from '@/componants/AfterHero'
import AfterAfterHero from '@/componants/AfterAfterHero'
import AfterAfterAfterHero from '@/componants/AfterAfterAfterHero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Journey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Header />
        <Hero />
        <AfterHero />
        <AfterAfterHero />
        <AfterAfterAfterHero />

      </main>
    </>
  )
}


